name: Attendance Bot (출석 봇)

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "thdwoqor"
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: '0 3,9,15,21 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    
    - name: Install ubuntu package
      run: |        
        sudo apt-get install fonts-unfonts-core
        sudo apt-get install fonts-unfonts-extra
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add        
        sudo apt-get install google-chrome-stable    
        wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
        unzip ./chromedriver_linux64.zip   

    - name: Create .env file
      run: |
        jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}

    - name: Run run.py
      run: |
        python run.py

    - name: Commit
      run: |
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git config user.name 'github-actions[bot]'
        git add .
        if [ -z "$(git status --porcelain)" ]; then echo "Nothing changed"; else git commit -m "bot: update files"; fi

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $